# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ef6416e14d740c526a2ad07fa4699b6dc5ffb7236ff129e969c040488425751b6af3d08c08b27c0ed7c71b9403dc088f355b06b13eb93fc74e25764c69d5d24

test:
  secret_key_base: b003af2144a5d05b7b0fefe696fd2b112df7a4a2dd696cfaac317a0a3a8fa83ce3475d15aa48a26c7af95575d55870dcad548b069ce166f8acd04d87f9af9e17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
